[package]
name = "cozydot"
version = "0.0.1"
edition = "2021"
rust-version = "1.85"
description = "Declarative Linux post-install, update, and dotfile manager"
license = "MIT"
repository = "https://github.com/adoreblvnk/cozydot"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_path_to_error = "0.1"
serde_yaml = "0.9"
serde_json = "1"
sha2 = "0.10"
tempfile = "3"
regex = "1"
rustix = { version = "1.1", features = ["fs", "process"] }
url = "=2.5.7"
yaml-rust2 = "0.11"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
