# https://github.com/Macchina-CLI/macchina/blob/main/doc/macchina.7.scd
spacing         = 2
padding         = 0
hide_ascii      = true
separator       = "\u2665"

[palette]
glyph           = "\uf111 "
visible         = true

[box]
border          = "rounded"
visible         = true
inner_margin.x  = 5
inner_margin.y  = 0

[randomize]
key_color       = true
separator_color = true

[keys]
host            = "\uf015  Host"
kernel          = "\uf31a  Kernel"
battery         = "\uf240  Battery"
os              = "OS"
de              = "\uf26c  DE"
wm              = "\ueb7f  WM"
distro          = "\uef88  Distro"
terminal        = "\uea85  Terminal"
shell           = "\ue691  Shell"
packages        = "\ueb29  Packages"
uptime          = "\uf2f2  Uptime"
memory          = "\uefc5  Memory"
machine         = "\uf109  Machine"
local_ip        = "IP"
backlight       = "\uf185  Brightness"
resolution      = "\uf030  Resolution"
cpu_load        = "\ued93  CPU Load"
cpu             = "\uf4bc  CPU"
gpu             = "\uf4bc  GPU"
disk_space      = "Disk Space"
