#!/bin/sh
if [ "$(uname)" = "Linux" ]; then
  if command -v pinentry-tty >/dev/null 2>&1; then
    exec pinentry-tty "$@"
  fi
  # fallback to gui default
  exec pinentry-gnome3 "$@"
fi

if [ -t 0 ] || [ -n "$GPG_TTY" ]; then
  exec /opt/homebrew/bin/pinentry-tty "$@"
fi

# fallback to gui default
exec /opt/homebrew/bin/pinentry-mac "$@"
