# see https://github.com/alacritty/alacritty-theme
general.import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]

[window]
dimensions = { columns = 140, lines = 40 }
dynamic_padding = true
opacity = 0.90

[font]
normal = { family = "GeistMono NF", style = "Regular" }
bold = { family = "GeistMono NF", style = "Bold" }
italic = { family = "GeistMono NF", style = "Italic" }
bold_italic = { family = "GeistMono NF", style = "Bold Italic" }

[cursor]
style = { blinking = "On" }
