metadata:
  description: CLI utilities only. For use with WSL2 too.
  distro: auto # auto | ubuntu | debian | linuxmint
  DE: auto     # auto | gnome | cinnamon
check:
  distroCfg: true # supports ubuntu / debian / linuxmint
  purge: !disabled
    # docker installed via aptAltSources
    - docker.io
    - docker-doc
    - docker-compose
    - docker-compose-v2
    - podman-docker
    - containerd
    - runc
    - "*firefox*"     # firefox installed via aptAltSources
    - "*libreoffice*" # libreoffice replaced with onlyoffice
  deps: !enabled
    # essential packages
    - apt-transport-https
    - bash-completion
    - build-essential
    - ca-certificates
    - cmake
    - curl
    - ffmpeg
    - flatpak
    - git
    - software-properties-common
    - stow
    - ttf-mscorefonts-installer
    # pyenv dependencies
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncurses-dev # libncursesw5-dev is a transitional pkg
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - tk-dev
    - xz-utils
    - zlib1g-dev
    # imagemagick dependencies
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    # docker dependencies
    - lsb-release
    # cargo-update dependencies
    - libgit2-dev
    - libssh-dev
    - libssl-dev
    - pkgconf
    # alacritty dependencies
    - libfontconfig1-dev
    - libfreetype-dev # libfreetype6-dev is a transitional pkg
    - libxcb-xfixes0-dev
    - libxkbcommon-dev
    # - pkg-config # NOTE: pkgconf breaks pkg-config (>= 0.29-1)
  python: !enabled
    pyenvUpdate: false
    version: latest # latest | <major>[.<minor>]
    pip: false
  rustupCheck: true
  appimaged: !enabled
    cleanInstall: false
  nerdfont: !enabled GeistMono # https://www.nerdfonts.com/font-downloads
install:
  check: true
  apt: !enabled
    # CLI utils
    - fzf         # fuzzy finder
    - gnupg2
    - openssh-server
    - pass
    - trash-cli
    - vim
    # multimedia
    - imagemagick # image converter
    - pandoc      # document converter
    - vlc
  addRepos: !enabled
    - sourceName: docker
      remoteKey: https://download.docker.com/linux/${UPSTREAM_DISTRO}/gpg
      keyPath: /etc/apt/keyrings/docker.asc
      repo: deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/${UPSTREAM_DISTRO} $VERSION_CODENAME stable
      pinning: false
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
  flatpak: !disabled
    - com.discordapp.Discord
  cargo: !enabled
    - alacritty
    - bat --locked      # cat replacement
    - bottom --locked   # process / system monitor
    - du-dust
    - eza               # ls replacement
    - fd-find
    - macchina          # system info
    - ripgrep
    - starship --locked
    - yazi-cli --locked # terminal file manager
    - yazi-fm --locked
    - zellij --locked
    - zoxide --locked   # smarter cd command
  binaries: !enabled
    - name: git-credential-manager.deb
      url: $(curl -sSL https://api.github.com/repos/git-ecosystem/git-credential-manager/releases/latest | yq '.assets[].browser_download_url | select(. == "*deb")')      
  languages:
    goVersion: !enabled latest   # latest | <major>.<minor>.<patch>
    nodeVersion: !enabled latest # latest | <major>[.<minor>[.<patch>]]
update:
  check: true
  apt: !enabled
    aptFull: false
  flatpak: true
  cargo: false
  other:
    yq: true
    go: false
    node: false
    zellijClear: true
configure:
  check: true
  dotfiles: !enabled
    stowMode: override # override | backup
    packages:
      - bash
      - alacritty
      - bat
      - bottom
      - macchina
      - starship
      - yazi
      - zellij
  apps:
    alacritty: true
    docker: false
    virtualbox: false
    vscode:
      extensions: !disabled
        - catppuccin.catppuccin-vsc
  optimisations: !disabled
    auto-cpufreq: false
  DE: !disabled
    cinnamon:
      defaultTerm: !enabled alacritty
      plankDock: true
      panelToMenuBar: true
      gTile: true
    gnome:
      settings: true
      extensions: !enabled
        # - dash-to-dock@micxgx.gmail.com # Ubuntu already has a conflicting pkg
        - rounded-window-corners@fxgn
      defaultTerm: !enabled alacritty
      MacOSDock: true
      smoothRoundedCorners: true
