metadata:
  description: CLI utilities only. For use with WSL2 too.
  distro: auto
  DE: auto
check:
  distroCfg: true
  purge: !disabled
    # docker installed via aptAltSources
    - docker.io
    - docker-doc
    - docker-compose
    - docker-compose-v2
    - podman-docker
    - containerd
    - runc
    - "*firefox*" # firefox installed via aptAltSources
    - "*libreoffice*" # libreoffice replaced with onlyoffice
  deps: !enabled
    # essential packages
    - apt-transport-https
    - bash-completion
    - build-essential
    - ca-certificates
    - cmake
    - curl
    - ffmpeg
    - flatpak
    - git
    - pinentry-tty
    - software-properties-common
    - stow
    - ttf-mscorefonts-installer
    # pyenv dependencies
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncurses-dev # libncursesw5-dev is a transitional pkg
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - tk-dev
    - xz-utils
    - zlib1g-dev
    # imagemagick dependencies
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    # cargo-update dependencies
    - libgit2-dev
    - libssh-dev
    - libssl-dev
    - pkgconf
    # alacritty dependencies
    - libfontconfig1-dev
    - libfreetype-dev # libfreetype6-dev is a transitional pkg
    - libxcb-xfixes0-dev
    - libxkbcommon-dev
    # - pkg-config # NOTE: pkgconf breaks pkg-config (>= 0.29-1)
  pyenv: !enabled
    update: false
    version: 3
    pip: true
  uv: !disabled
    version: !enabled 3.13
  rustupCheck: true
  appimaged: false
  nerdfont: !enabled GeistMono
install:
  check: true
  apt: !enabled
    - default-jdk
    - fzf # fuzzy finder
    - gnupg2
    - imagemagick # image converter
    - openssh-server
    - pandoc # document converter
    - pass
    - trash-cli
    - vim
    - vlc
  addRepos: !enabled
    - sourceName: github-cli
      remoteKey: https://cli.github.com/packages/githubcli-archive-keyring.gpg
      keyPath: /etc/apt/keyrings/githubcli-archive-keyring.gpg
      repo: deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main
      pinning: false
      packages:
        - gh
  flatpak: !disabled []
  cargo: !enabled
    - bat --locked # cat replacement
    - bottom --locked # process / system monitor
    - du-dust # du alternative
    - eza # ls replacement
    - fd-find # find alternative
    - macchina # system info
    - starship --locked
    - tealdeer
    - yazi-cli --locked # terminal file manager
    - yazi-fm --locked
    - zellij --locked # terminal multiplexer
    - zoxide --locked # smarter cd command
  binaries: !enabled
    - name: git-credential-manager.deb
      url: $(curl -sSL https://api.github.com/repos/git-ecosystem/git-credential-manager/releases/latest | yq '.assets[].browser_download_url | select(. == "*deb")')
  languages:
    goVersion: !enabled latest
    nodeVersion: !enabled latest
update:
  check: true
  apt: !enabled
    aptFull: false
  flatpak: true
  cargo: false
  other:
    yq: true
    go: false
    node: false
    zellijClear: true
configure:
  check: true
  dotfiles: !enabled
    stowMode: override
    packages:
      - bash
      - bat
      - bottom
      - macchina
      - starship
      - yazi
      - zellij
  apps:
    alacritty: false
    docker: true
    virtualbox: false
    vscodeExtensions: !disabled []
  desktopEnvironment: !disabled
    common: !enabled
      defaultTerm: !enabled alacritty
      tag: '!disabled'
    gnome: !enabled
      settings: true
      extensions: !enabled
        # - dash-to-dock@micxgx.gmail.com # Ubuntu already has a conflicting pkg
        - blur-my-shell@aunetx
        - netspeedsimplified@prateekmedia.extension
        - rounded-window-corners@fxgn
      MacOSDock: true
      smoothRoundedCorners: true
      tag: '!disabled'
    cinnamon: !enabled
