version: 0.0.1
metadata:
  description: Sensible defaults for tides.
  # NOTE: the following values are highly recommended to be set to "auto"
  distro: auto # auto | ubuntu | linuxmint | debian
  DE: auto # auto | gnome | cinnamon
check:
  distroCfg:
    ubuntu: true
    linuxmint: true
    debian: true
  purge: !disabled
    # docker installed via aptAltSources
    - docker.io
    - docker-doc
    - docker-compose
    - docker-compose-v2
    - podman-docker
    - containerd
    - runc
    - "*firefox*" # firefox installed via aptAltSources
    - "*libreoffice*" # libreoffice replaced with onlyoffice
  deps: !enabled
    # essential packages
    - apt-transport-https
    - bash-completion
    - build-essential
    - ca-certificates
    - cmake
    - curl
    - ffmpeg
    - flatpak
    - git
    - software-properties-common
    - stow
    - ttf-mscorefonts-installer
    # pyenv dependencies
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncurses-dev # libncursesw5-dev is a transitional pkg
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libxml2-dev
    - libxmlsec1-dev
    - tk-dev
    - xz-utils
    - zlib1g-dev
    # imagemagick dependencies
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    # docker dependencies
    - lsb-release
    # cargo-update dependencies
    - libgit2-dev
    - libssh-dev
    - libssl-dev
    - pkgconf
    # alacritty dependencies
    - libfontconfig1-dev
    - libfreetype-dev # libfreetype6-dev is a transitional pkg
    - libxcb-xfixes0-dev
    - libxkbcommon-dev
    # - pkg-config # NOTE: pkgconf breaks pkg-config (>= 0.29-1)
  python: !enabled
    pyenvUpdate: false
    version: latest # latest | <major>[.<minor>]
    pip: false
  rustupCheck: true
  appimaged: !enabled
    cleanInstall: false
  nerdfont: !enabled GeistMono # list of nerdfonts: https://www.nerdfonts.com/font-downloads
install:
  check: true
  apt: !enabled
    # CLI utils
    - fzf # fuzzy finder
    - gnupg2
    - openssh-server
    - pass
    - trash-cli
    - vim
    # apps
    - nautilus # file manager
    # multimedia
    - imagemagick # image converter
    - pandoc # document converter
    - vlc
  addRepos: !enabled
    - sourceName: docker
      remoteKey: https://download.docker.com/linux/${UPSTREAM_DISTRO}/gpg
      keyPath: /etc/apt/keyrings/docker.asc
      repo: deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/${UPSTREAM_DISTRO} $VERSION_CODENAME stable
      pinning: false
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - sourceName: mozilla
      remoteKey: https://packages.mozilla.org/apt/repo-signing-key.gpg
      keyPath: /etc/apt/keyrings/packages.mozilla.org.asc
      repo: deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main
      pinning: |-
        Package: *
        Pin: origin packages.mozilla.org
        Pin-Priority: 1000
      packages:
        - firefox
    - sourceName: onlyoffice
      remoteKey: https://download.onlyoffice.com/GPG-KEY-ONLYOFFICE
      keyPath: /usr/share/keyrings/onlyoffice.gpg
      repo: deb [signed-by=/usr/share/keyrings/onlyoffice.gpg] https://download.onlyoffice.com/repo/debian squeeze main
      pinning: false
      packages:
        - onlyoffice-desktopeditors
    - sourceName: virtualbox
      remoteKey: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      keyPath: /usr/share/keyrings/oracle-virtualbox-2016.asc
      repo: deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.asc] https://download.virtualbox.org/virtualbox/debian $VERSION_CODENAME contrib
      pinning: false
      packages:
        - virtualbox-7.0
    - sourceName: vscode
      remoteKey: https://packages.microsoft.com/keys/microsoft.asc
      keyPath: /etc/apt/keyrings/packages.microsoft.gpg
      repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
      pinning: false
      packages:
        - code
  flatpak: !enabled
    - com.discordapp.Discord
    - com.obsproject.Studio # video recorder & live streaming software
    - io.bassi.Amberol # music player
    - org.qbittorrent.qBittorrent
    - org.shotcut.Shotcut # video editor
    - org.telegram.desktop
  cargo: !enabled
    - alacritty
    - bat --locked # cat replacement
    - bottom --locked # process / system monitor
    - du-dust
    - eza # ls replacement
    - fd-find
    - macchina # system info
    - ripgrep
    - starship --locked
    - yazi-cli --locked # terminal file manager
    - yazi-fm --locked
    - zellij --locked
    - zoxide --locked # smarter cd command
  binaries: !enabled
    - name: git-credential-manager.deb
      url: $(curl -sSL https://api.github.com/repos/git-ecosystem/git-credential-manager/releases/latest | yq '.assets[].browser_download_url | select(. == "*deb")')      
    - name: Bitwarden.AppImage # password manager
      url: https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=appimage
    - name: drawio.AppImage # diagramming tool
      url: $(curl -sSL https://api.github.com/repos/jgraph/drawio-desktop/releases/latest | yq '.assets[].browser_download_url | select(. == "*x86_64*AppImage")')
    - name: Obsidian.AppImage # note-taking app
      url: $(curl -sSL https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest | yq '.assets[].browser_download_url | select(. == "*AppImage" and . != "*arm64*")')
    - name: zen.AppImage
      url: $(curl -sSL https://api.github.com/repos/zen-browser/desktop/releases/latest | yq '.assets[].browser_download_url | select(. == "*specific.AppImage")')
  languages:
    goVersion: !enabled latest # latest | <major>.<minor>.<patch>
    nodeVersion: !enabled latest # latest | <major>[.<minor>[.<patch>]]
update:
  check: true
  apt: !enabled
    aptFull: false
  flatpak: true
  cargo: false
  other:
    yq: true
    go: false
    node: false
    zellijClear: true
configure:
  check: true
  dotfiles: !enabled
    stowMode: override # override | backup
    packages:
      - bash
      - alacritty
      - bat
      - bottom
      - macchina
      - starship
      - ulauncher
      - vscode
      - yazi
      - zellij
  apps:
    alacritty: true
    docker: true
    virtualbox: true
    vscode:
      extensions: !enabled
        - catppuccin.catppuccin-vsc
        - christian-kohler.path-intellisense
        - eamodio.gitlens
        - ecmel.vscode-html-css
        - esbenp.prettier-vscode
        - foxundermoon.shell-format
        - golang.go
        - ms-python.black-formatter
        - ms-python.debugpy
        - ms-python.isort
        - ms-python.python
        - ms-python.vscode-pylance
        - redhat.vscode-yaml
        - streetsidesoftware.code-spell-checker
        - visualstudioexptteam.intellicode-api-usage-examples
        - visualstudioexptteam.vscodeintellicode
        - wayou.vscode-todo-highlight
        - yzhang.markdown-all-in-one
  optimisations: !enabled
    auto-cpufreq: true # laptop
  DE: !enabled
    cinnamon:
      defaultTerm: !enabled alacritty
      plankDock: true
      panelToMenuBar: true
      gTile: !enabled
        tilingLayout: true
    gnome:
      settings: true
      extensions: !enabled
        # - dash-to-dock@micxgx.gmail.com # Ubuntu already has a conflicting pkg
        - blur-my-shell@aunetx
        - netspeedsimplified@prateekmedia.extension
        - rounded-window-corners@fxgn
      defaultTerm: !enabled alacritty
      MacOSDock: true
      smoothRoundedCorners: true
