version: 0.0.1
metadata:
  description: Sensible defaults for tides.
  skipSlow: false
  # NOTE: the following values are highly recommended to be set to "auto"
  distro: auto # auto | ubuntu | linuxmint | debian
  desktopEnvironment: auto # auto | gnome | cinnamon
config:
  check:
    distroCfg:
      ubuntu: true
      linuxmint: true
      debian: true
    purge: !enabled # NOTE: also disabled by metadata.skipSlow
      # docker installed via aptAltSources
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
      - firefox* # firefox installed via aptAltSources
      - libreoffice* # libreoffice replaced with onlyoffice
    deps: !enabled
      # essential packages
      - apt-transport-https
      - bash-completion
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - ffmpeg
      - flatpak
      - git
      - software-properties-common
      - stow
      - ttf-mscorefonts-installer
      # pyenv dependencies
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - tk-dev
      - xz-utils
      - zlib1g-dev
      # imagemagick dependencies
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      # docker dependencies
      - lsb-release
      # cargo-update dependencies
      - libgit2-dev
      - libssh-dev
      - libssl-dev
      - pkgconf
      # alacritty dependencies
      - libfontconfig1-dev
      - libfreetype6-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      # - pkg-config # NOTE: pkgconf breaks pkg-config (>= 0.29-1)
    python: !enabled
      pyenvUpdate: false
      version: 3.12 # <major>[.<minor>]
      pip: false
    rustupCheck: true
    appimaged: !enabled
      cleanInstall: false
    geistFontEnabled: true # NOTE: also disabled by metadata.skipSlow
    # list of nerdfonts: https://www.nerdfonts.com/font-downloads
    nerdfont: !enabled GeistMono # NOTE: also disabled by metadata.skipSlow
  install:
    check: true
    apt: !enabled
      # CLI utils
      - fzf # fuzzy finder
      - gnupg2
      - openssh-server
      - trash-cli
      - vim
      - xclip # terminal X11 clipboard
      # apps
      - flameshot # screenshot
      - nautilus # file manager
      # multimedia
      - imagemagick # image converter
      - pandoc # document converter
      - vlc
    addRepos: !enabled # NOTE: also disabled by metadata.skipSlow
      - sourceName: brave-browser-release
        remoteGpgKey: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        gpgKeyPath: /usr/share/keyrings/brave-browser-archive-keyring.gpg
        repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main
        pinning: false
        packages:
          - brave-browser
      - sourceName: docker
        remoteGpgKey: https://download.docker.com/linux/ubuntu/gpg
        gpgKeyPath: /etc/apt/keyrings/docker.asc
        repo: deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $VERSION_CODENAME stable
        pinning: false
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
      - sourceName: mozilla
        remoteGpgKey: https://packages.mozilla.org/apt/repo-signing-key.gpg
        gpgKeyPath: /etc/apt/keyrings/packages.mozilla.org.asc
        repo: deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main
        pinning: |-
          Package: *
          Pin: origin packages.mozilla.org
          Pin-Priority: 1000
        packages:
          - firefox
      - sourceName: onlyoffice
        remoteGpgKey: https://download.onlyoffice.com/GPG-KEY-ONLYOFFICE
        gpgKeyPath: /usr/share/keyrings/onlyoffice.gpg
        repo: deb [signed-by=/usr/share/keyrings/onlyoffice.gpg] https://download.onlyoffice.com/repo/debian squeeze main
        pinning: false
        packages:
          - onlyoffice-desktopeditors
      - sourceName: virtualbox
        remoteGpgKey: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        gpgKeyPath: /usr/share/keyrings/oracle-virtualbox-2016.asc
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.asc] https://download.virtualbox.org/virtualbox/debian $VERSION_CODENAME contrib
        pinning: false
        packages:
          - virtualbox-7.0
      - sourceName: vscodium
        remoteGpgKey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        gpgKeyPath: /usr/share/keyrings/vscodium-archive-keyring.gpg
        repo: deb [signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg] https://download.vscodium.com/debs vscodium main
        pinning: false
        packages:
          - codium
    flatpak: !enabled
      - com.discordapp.Discord
      - com.obsproject.Studio # video recorder & live streaming software
      - org.qbittorrent.qBittorrent
      - org.shotcut.Shotcut # video editor
      - org.telegram.desktop
    cargo: !enabled
      - alacritty
      - bat --locked # cat replacement
      - bottom --locked # process / system monitor
      - du-dust
      - eza # ls replacement
      - fd-find
      - macchina # system info
      - ripgrep
      - starship --locked
      - yazi-cli --locked # terminal file manager
      - yazi-fm --locked # terminal file manager
      - zellij --locked
      - zoxide --locked # smarter cd command
    binaries: !enabled
      - name: Bitwarden.AppImage # password manager
        url: https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=appimage
      - name: drawio.AppImage # diagramming tool
        url: $(curl -sSL https://api.github.com/repos/jgraph/drawio-desktop/releases/latest | yq '.assets[].browser_download_url | select(. == "*x86_64*AppImage")')
      - name: Obsidian.AppImage # note-taking app
        url: $(curl -sSL https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest | yq '.assets[].browser_download_url | select(. == "*AppImage" and . != "*arm64*")')
      - name: ulauncher.deb
        url: $(curl -sSL https://api.github.com/repos/Ulauncher/Ulauncher/releases/latest | yq '.assets[].browser_download_url | select(. == "*deb")')
      # - name: zen.AppImage
      #   url: $(curl -sSL https://api.github.com/repos/zen-browser/desktop/releases/latest | yq '.assets[].browser_download_url | select(. == "*specific.AppImage")')
    languages:
      goVersion: !enabled latest # latest | <major>.<minor>.<patch>
      nvm: !enabled
        nodeVersion: 20 # <major>[.<minor>]
  update:
    check: true
    apt: !enabled
      aptFull: false # NOTE: apt must be true for aptFull to take effect
    flatpak: true
    cargo: true # NOTE: also disabled by metadata.skipSlow
    other:
      go: false
      yq: true
      zellijClear: true
  configure:
    check: true
    dotfiles: !enabled
      stowMode: override # backup | override
      packages:
        - alacritty
        - bash
        - bat
        - bottom
        - codium
        # - extras
        - macchina
        - starship
        - ulauncher
        - yazi
        - zellij
    apps:
      git:
        userInfo: true # NOTE: set actual contents in secrets.yaml
      alacritty: true
      docker: true
      ulauncher: true
      virtualbox: true
      vscodium:
        extensions: !enabled # NOTE: also disabled by metadata.skipSlow
          - adpyke.codesnap
          - catppuccin.catppuccin-vsc
          - catppuccin.catppuccin-vsc-icons
          - christian-kohler.path-intellisense
          - eamodio.gitlens
          - ecmel.vscode-html-css
          - esbenp.prettier-vscode
          - foxundermoon.shell-format
          - ms-python.black-formatter
          - ms-python.debugpy
          - ms-python.isort
          - ms-python.python
          - redhat.vscode-yaml
          - streetsidesoftware.code-spell-checker
          - timonwong.shellcheck
          - wayou.vscode-todo-highlight
          - yzhang.markdown-all-in-one
    optimisations: !enabled
      auto-cpufreq: true # laptop
    DEConf: !enabled
      cinnamon:
        defaultTerm: !enabled alacritty
        plankDock: true
        panelToMenuBar: true
        flameshot: true
        gTile: !enabled
          tilingLayout: true
      gnome:
        tweaksAndExtensions: true
        defaultTerm: !enabled alacritty
        MacOSDock: true
        flameshot: true
